# Generated by Django 3.0 on 2019-12-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, help_text='client is the main type of users.', verbose_name='client'),
        ),
    ]
