# Generated by Django 3.0 on 2019-12-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.CharField(error_messages={'unique': "There is a catalogue whith the same 'slug_name'"}, max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
