# Generated by Django 3.0 on 2019-12-10 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcatalogue',
            name='catalogue_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
